alias ..2="cd ../.."
alias ..3="cd ../../.."
alias ls="ls -Al"
alias lt="ls -lt"
alias ltr="ls -ltr"
alias mkdir="mkdir -pv"
alias tgz="tar -xzvf"
alias g="git"
alias qq="exit"

# opensuse / zypper
alias ox="dolphin ."
alias zdup="sudo zypper dup -l"
alias zlu="zypper lu"
alias zfresh="sudo zypper refresh"
alias zal="sudo zypper al"
alias zal="sudo zypper rl"
alias zin="sudo zypper in"
alias zrm="sudo zypper rm"
